### ISSUE TITLE
Permalinks not working on Chrome

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/mtlynch.io#160]
I think some of the recent layout changes affected permalinks because they no longer seem to load the correct heading. For example, this URL:

https://mtlynch.io/sia-nextcloud/#launch-containers

Brings me to here, which is a few paragraphs from the "Launch Containers" heading:

![image](https://user-images.githubusercontent.com/7783288/30947783-9e892d8a-a3d9-11e7-8646-4b6f1a9c3da6.png)

It seems to work fine on Edge and Firefox, just not Chrome (specifically, v61 on Win10 x64).

**Comment by shredtechular** [comment]
Good catch, I didn't even notice this... I can replicate this on my end and am working on it now.

**Comment by mtlynch** [comment]
This was partially fixed by #163, but as @shredtechular notes, there are still places where we see inconsistent behavior:

https://mtlynch.io/sia-nextcloud/#nextcloud
https://mtlynch.io/greenpithumb/#deployment

Obviously the ideal would be if we could get the permalinks working consistently in all browsers, but at the same time, it's obviously not worth infinite engineering effort to make that happen.

@shredtechular - Are there other potential avenues you could explore here? Do you think there's a chance of progress if you spent another 4-5 hours on this?

**Comment by shredtechular** [comment]
Sorry, my PR may not have been completely clear... I was seeing inconsistent behavior _before_ the fix was merged for #163.

Those anchor links are working properly for me now in all the browsers that I can test with on my end including Chrome v61.x on Win10 (MS Surface, at least).  The catch is the page does need to load all of its assets first, but once the assets are loaded, the page should scroll down to the anchor permalink and in the correct spot now.

Is it still not working for you even after the PR merge?

**Comment by mtlynch** [comment]
Oh, sorry, I misread it. I tested the links you referenced and I was like, "Yep, still seeing inconsistent behavior," and then completely forgot that I was testing on prod and I hadn't merged in the fix yet.

Now that the fix is in, behavior is all working as desired. Thanks!

**Comment by shredtechular** [comment]
Nice that is awesome!!
